spring:
  application:
    name: academia
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/STUDY
    username: postgres
    password: 1234